[build]
    # ignore all PRs opened by `dependabot` (with last commit made by `dependabot`)
    ignore = 'git log -1 --pretty=%B | grep dependabot'

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "https://plugin-acessibilidade.web.app/main.js"
    status = 200

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"